### ISSUE TITLE
Не синхронизируется часть парков

### ISSUE THREAD

**Issue by xakepok** [xakepok/mgt#2]
Нет:
8ап: id1001***
1ап: id100***
17ап: id1017***

**Comment by xakepok** [comment]
Нужно узнать подробнее про 1 парк, каких машин нет? Номера машин, ид и маршрутов.
17 парк есть/

**Comment by MigVal124** [comment]
1ап нет десятков машин, типичные I'd
010159
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100033
010459
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100011
И в таком духе.
18ап отсутствует почти полностью, типичное id
010704
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100391
010671
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100165
Машины с id более 1000 в базе есть, нумерация в одном диапазоне с отсутствующими 8ап

С 17ап все в порядке, вроде все машины есть, просто его не было в списке парков)

**Comment by xakepok** [comment]
Вот, теперь понятно) Добавлю)

**Comment by xakepok** [comment]
> 1ап нет десятков машин, типичные I'd
010159
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100033
010459
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100011
И в таком духе.
18ап отсутствует почти полностью, типичное id
010704
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100391
010671
http://moscow.map.office.transnavi.ru/wap/online/?srv_id=1&uniqueid=100165

У этих машин на нави не указан бортовой номер, потому они не синхронизируются.

**Comment by MigVal124** [comment]
Отображались, этой ночью просто нави сдохла)

**Comment by xakepok** [comment]
Ну вот они есть у меня в списке на синхронизацию) раз нави сдохла - то естественно, что их нет. Посмотрим этой ночью

**Comment by xakepok** [comment]
Проблема устранена в версии 1.2.2

**Comment by MigVal124** [comment]
По найденному на данный момент:
ФВ(4) - нет машин с id более 5000
ФЗ(15) - нет машин с id более 16000, новые машины с ним, впереди ещё полная перенумерация
ФЦ(8) - нет машин с id 1101***
ФЮЗ(1) - нет машин с I'd 1001***

Остутствует несколько десятков трамвае со странными id с номерами в диапазоне где-то от 1 до 400

Остальное вроде в порядке, новые машины в 16 и 19 парках отображаются
